### ISSUE TITLE
Fails to update

### ISSUE THREAD

**Issue by jamierocks** [pyupio/statuspage#19]
see https://github.com/Lexteam/StatusPage/issues/2 and http://status.lexteam.xyz/

I even recreated the issue again :S

**Comment by skyzyx** [comment]
Likewise, I'm seeing this message when running `statuspage update --token={token} --name={name-of-status-repo}`

```plain
Generating..
Traceback (most recent call last):
  File "<string>", line 257, in <module>
  File "site-packages/click/core.py", line 716, in __call__
  File "site-packages/click/core.py", line 696, in main
  File "site-packages/click/core.py", line 1060, in invoke
  File "site-packages/click/core.py", line 889, in invoke
  File "site-packages/click/core.py", line 534, in invoke
  File "<string>", line 56, in update
  File "<string>", line 65, in run_update
  File "github/AuthenticatedUser.py", line 845, in get_repo
  File "github/Requester.py", line 171, in requestJsonAndCheck
  File "github/Requester.py", line 179, in __check
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
statuspage returned -1
```

* OS X 10.11.3 (15D21)
* Python 2.7.11

**Comment by chandanjog** [comment]
See the same issue. Does not seem to update the page.

**Comment by chandanjog** [comment]
Fails for both osx and linux statuspage update calls

**Comment by narcotk** [comment]
I am seeing this on RHEL 6 & 7, and Centos 6 & 7 too.  With the "pip install statuspage" and the downloaded binary.
