### ISSUE TITLE
Error while upgrading with 0.3 pre-release

### ISSUE THREAD

**Issue by Art4** [pyupio/statuspage#29]
I've tried to upgrade the statuspage with the 0.3 pre release but stumbled upon this error:

```
$ ./statuspage upgrade --name=StatusPage --token=...
Editing files:  50%|█████████████████████████████████████████▌                                         | 1/2 [00:01<00:01,  1.85s/it]Traceback (most recent call last):
  File "<string>", line 193, in <module>
  File "site-packages/click/core.py", line 716, in __call__
  File "site-packages/click/core.py", line 696, in main
  File "site-packages/click/core.py", line 1060, in invoke
  File "site-packages/click/core.py", line 889, in invoke
  File "site-packages/click/core.py", line 534, in invoke
  File "<string>", line 61, in upgrade
  File "<string>", line 87, in run_upgrade
  File "github/Repository.py", line 1218, in get_file_contents
  File "github/Requester.py", line 171, in requestJsonAndCheck
  File "github/Requester.py", line 179, in __check
github.GithubException.UnknownObjectException: 404 {'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}
statuspage returned -1
```

**Comment by jayfk** [comment]
Have you moved `style.css` from the root directory?

**Comment by Art4** [comment]
Yes, you are right. I moved the files back to root and the upgrade works fine. Thank you.
